spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zybe/config.git
  rabbitmq:
    host: ${host:192.168.58.167}
    port: ${port:5672}
    username: zybe
    password: zybe
  application:
    name: config

server:
  port: 9100