server:
  port: ${port:8761}
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${potr:8761}/eureka
    fetch-registry: ${fetch:false}
    register-with-eureka: ${register:false}
